### ISSUE TITLE
We want you to stop depending on https://github.com/golang/mock

### ISSUE THREAD

**Issue by yomaisch** [oxyno-zeta/gomock-extra-matcher#27]
**Is your feature request related to a problem? Please describe.**
Your package depends on https://github.com/golang/mock, but https://github.com/golang/mock became read-only on June 28, 2023.

My project has also switched to https://github.com/uber-go/mock, but I am concerned about continuing to use your package because your package still depends on package A.

**Describe the solution you'd like**
I want them to stop relying on https://github.com/golang/mock and switch to https://github.com/uber-go/mock.

**Describe alternatives you've considered**

**Additional context**

**Comment by oxyno-zeta** [comment]
Hello @yomaisch ,

Thanks for the issue.
For sure I will made this change.
I didn't see the read-only on main repository before... 

Best Regards,

**Comment by oxyno-zeta** [comment]
Hello @yomaisch ,

I've just released the v1.2.0 with the switch !

Thanks for the issue

**Comment by yomaisch** [comment]
Hello @oxyno-zeta ,
Thank you for your prompt response !
